name: Deploy

on:
  push:
    branches: [deploy/v1.1.0]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mark-agenda-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mark-agenda-api:1.1.0
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mark-agenda-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mark-agenda-api:buildcache,mode=max
